// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBovUDMHkKlfPU2of32XRi6Zsc4lOHohfI',
    appId: '1:585301765096:android:1b70b8d5b58c78df28525d',
    messagingSenderId: '585301765096',
    projectId: 'booking-15f1b',
    storageBucket: 'booking-15f1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpswQSKuokbeBS6qw2VAC4uKVUL1zSxDg',
    appId: '1:585301765096:ios:c95d066cd790652928525d',
    messagingSenderId: '585301765096',
    projectId: 'booking-15f1b',
    storageBucket: 'booking-15f1b.appspot.com',
    androidClientId: '585301765096-lep2lr0pgpb2lfgqrlqqa3nb68vfup8c.apps.googleusercontent.com',
    iosClientId: '585301765096-pglp434ies2hs18us6dokb082rmtra0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNoteAppHive',
  );

}